Existe correlação entre a transmissão do COVID-19 e a densidade demográfica da população à nível municipal e estadual no Brasil?

R. Sim, dependendo da quantidade de pessoas, a contaminação é maior devido ao maior número de pessoas que um infectado pode entrar em contato, principalmente em locais de maior aglomeração (Transporte público: ônibus e metrô). (Eloiza)

In [2]:
import pandas as pd

In [17]:
corona = pd.read_csv('../tabelas_test/COVID19_REGIOES BR.csv', sep=';')
corona_BR = corona[(corona['estado'] == 'SP') & (corona['casosNovos']!=0)]
corona_BR

,regiao,estado,data,casosNovos,casosAcumulados,obitosNovos,obitosAcumulados
1243,Sudeste,SP,26/02/2020,1,1,0,0
1246,Sudeste,SP,29/02/2020,1,2,0,0
1250,Sudeste,SP,04/03/2020,1,3,0,0
1251,Sudeste,SP,05/03/2020,3,6,0,0
1252,Sudeste,SP,06/03/2020,4,10,0,0
1253,Sudeste,SP,07/03/2020,3,13,0,0
1254,Sudeste,SP,08/03/2020,3,16,0,0
1256,Sudeste,SP,10/03/2020,3,19,0,0
1257,Sudeste,SP,11/03/2020,11,30,0,0
1258,Sudeste,SP,12/03/2020,12,42,0,0
1259,Sudeste,SP,13/03/2020,14,56,0,0
1260,Sudeste,SP,14/03/2020,9,65,0,0
1261,Sudeste,SP,15/03/2020,71,136,0,0
1262,Sudeste,SP,16/03/2020,16,152,0,0
1263,Sudeste,SP,17/03/2020,12,164,1,1
1264,Sudeste,SP,18/03/2020,76,240,3,4
1265,Sudeste,SP,19/03/2020,46,286,0,4
1266,Sudeste,SP,20/03/2020,110,396,5,9
1267,Sudeste,SP,21/03/2020,63,459,6,15
1268,Sudeste,SP,22/03/2020,172,631,7,22
1269,Sudeste,SP,23/03/2020,114,745,8,30
1270,Sudeste,SP,24/03/2020,65,810,10,40
1271,Sudeste,SP,25/03/2020,52,862,8,48
1272,Sudeste,SP,26/03/2020,190,1052,10,58
1273,Sudeste,SP,27/03/2020,171,1223,10,68
1274,Sudeste,SP,28/03/2020,183,1406,16,84
1275,Sudeste,SP,29/03/2020,45,1451,14,98
1276,Sudeste,SP,30/03/2020,66,1517,15,113
1277,Sudeste,SP,31/03/2020,822,2339,23,136
1278,Sudeste,SP,01/04/2020,642,2981,28,164
1279,Sudeste,SP,02/04/2020,525,3506,24,188

In [21]:
#Ultima atualização de obito
corona_BR.loc[corona_BR.index.max(),'obitosAcumulados']

188

In [12]:
corona_municipio =  pd.read_csv('../tabelas_test/covid19_municipios.csv')
corona_municipio.head()

,date,state,city,place_type,confirmed,deaths,is_last,estimated_population_2019,city_ibge_code,confirmed_per_100k_inhabitants,death_rate
0,2020-04-03,AC,Acrelândia,city,9,0.0,True,15256.0,1200013.0,58.99318,NaN
1,2020-04-03,AC,Porto Acre,city,1,0.0,True,18504.0,1200807.0,5.40424,NaN
2,2020-04-03,AC,Rio Branco,city,36,0.0,True,407319.0,1200401.0,8.83828,NaN
3,2020-04-03,AC,NaN,state,46,0.0,True,881935.0,12.0,5.21580,NaN
4,2020-04-03,AL,Importados/Indefinidos,city,4,0.0,True,NaN,NaN,NaN,NaN

In [15]:
corona_municipio[(corona_municipio['state'] == 'SP') & (corona_municipio['city'] == 'São Paulo')]

,date,state,city,place_type,confirmed,deaths,is_last,estimated_population_2019,city_ibge_code,confirmed_per_100k_inhabitants,death_rate
540,2020-04-03,SP,São Paulo,city,3202,186.0,True,12252023.0,3550308.0,26.13446,0.0581
1068,2020-04-02,SP,São Paulo,city,2815,164.0,False,12252023.0,3550308.0,22.97580,0.0583
1551,2020-04-01,SP,São Paulo,city,2418,144.0,False,12252023.0,3550308.0,19.73552,0.0596
1997,2020-03-31,SP,São Paulo,city,1885,121.0,False,12252023.0,3550308.0,15.38521,0.0642
2402,2020-03-30,SP,São Paulo,city,1233,103.0,False,12252023.0,3550308.0,10.06364,0.0835
3307,2020-03-27,SP,São Paulo,city,1044,62.0,False,12252023.0,3550308.0,8.52104,0.0594
3586,2020-03-26,SP,São Paulo,city,899,53.0,False,12252023.0,3550308.0,7.33756,0.0590
3845,2020-03-25,SP,São Paulo,city,722,44.0,False,12252023.0,3550308.0,5.89290,0.0609
4640,2020-03-20,SP,São Paulo,city,306,9.0,False,12252023.0,3550308.0,2.49755,0.0294
4740,2020-03-19,SP,São Paulo,city,259,5.0,False,12252023.0,3550308.0,2.11394,0.0193
4834,2020-03-18,SP,São Paulo,city,214,NaN,False,12252023.0,3550308.0,1.74665,NaN
4891,2020-03-17,SP,São Paulo,city,156,1.0,False,12252023.0,3550308.0,1.27326,0.0064
4946,2020-03-16,SP,São Paulo,city,145,NaN,False,12252023.0,3550308.0,1.18348,NaN
4998,2020-03-14,SP,São Paulo,city,62,NaN,False,12252023.0,3550308.0,0.50604,NaN
5065,2020-03-12,SP,São Paulo,city,44,NaN,False,12252023.0,3550308.0,0.35912,NaN
5078,2020-03-11,SP,São Paulo,city,29,NaN,False,12252023.0,3550308.0,0.23670,NaN
5092,2020-03-10,SP,São Paulo,city,18,NaN,False,12252023.0,3550308.0,0.14691,NaN
5104,2020-03-09,SP,São Paulo,city,15,NaN,False,12252023.0,3550308.0,0.12243,NaN
5117,2020-03-08,SP,São Paulo,city,15,NaN,False,12252023.0,3550308.0,0.12243,NaN
5125,2020-03-07,SP,São Paulo,city,12,NaN,False,12252023.0,3550308.0,0.09794,NaN
5137,2020-03-05,SP,São Paulo,city,6,NaN,False,12252023.0,3550308.0,0.04897,NaN
5139,2020-03-04,SP,São Paulo,city,3,NaN,False,12252023.0,3550308.0,0.02449,NaN
5141,2020-03-03,SP,São Paulo,city,2,NaN,False,12252023.0,3550308.0,0.01632,NaN
5143,2020-03-02,SP,São Paulo,city,2,NaN,False,12252023.0,3550308.0,0.01632,NaN
5145,2020-03-01,SP,São Paulo,city,2,NaN,False,12252023.0,3550308.0,0.01632,NaN
5147,2020-02-29,SP,São Paulo,city,2,NaN,False,12252023.0,3550308.0,0.01632,NaN
5149,2020-02-28,SP,São Paulo,city,2,NaN,False,12252023.0,3550308.0,0.01632,NaN
5151,2020-02-27,SP,São Paulo,city,1,NaN,False,12252023.0,3550308.0,0.00816,NaN
5153,2020-02-26,SP,São Paulo,city,1,NaN,False,12252023.0,3550308.0,0.00816,NaN